// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BxCp64EYjkLRRHh-eKwL_vCNytWhnQw',
    appId: '1:889356957852:web:4336e20c7c3a573ce11559',
    messagingSenderId: '889356957852',
    projectId: 'teknik-b',
    authDomain: 'teknik-b.firebaseapp.com',
    storageBucket: 'teknik-b.firebasestorage.app',
    measurementId: 'G-302EVCX7D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCK3uRJJQpA3Oez0OTfOsAzKuMJdU1Kas',
    appId: '1:889356957852:android:12b3cf71cacb3241e11559',
    messagingSenderId: '889356957852',
    projectId: 'teknik-b',
    storageBucket: 'teknik-b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHsLxDlIvPQ1yFAWuaLcRiLoX3HosJBs',
    appId: '1:889356957852:ios:5758611e4e923c84e11559',
    messagingSenderId: '889356957852',
    projectId: 'teknik-b',
    storageBucket: 'teknik-b.firebasestorage.app',
    iosBundleId: 'com.example.teknik1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuHsLxDlIvPQ1yFAWuaLcRiLoX3HosJBs',
    appId: '1:889356957852:ios:5758611e4e923c84e11559',
    messagingSenderId: '889356957852',
    projectId: 'teknik-b',
    storageBucket: 'teknik-b.firebasestorage.app',
    iosBundleId: 'com.example.teknik1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6BxCp64EYjkLRRHh-eKwL_vCNytWhnQw',
    appId: '1:889356957852:web:af5240e881322a03e11559',
    messagingSenderId: '889356957852',
    projectId: 'teknik-b',
    authDomain: 'teknik-b.firebaseapp.com',
    storageBucket: 'teknik-b.firebasestorage.app',
    measurementId: 'G-L7N7CWCYS6',
  );
}
